import type { Breakdown } from "@/types/content";
import type { Locale } from "@/lib/i18n/config";

/**
 * Contenu placeholder — remplace par de vraies analyses de sites publics
 * (gym, restaurant, santé, immobilier, SaaS...) avant publication.
 */
const breakdownsByLocale: Record<Locale, Breakdown[]> = {
  fr: [
    {
      slug: "breakdown-gym",
      title: "[Nom de la salle de sport] — Website Review",
      category: "Gym",
      uxScore: 6,
      summary:
        "[Résumé du problème UX principal identifié sur ce site de salle de sport.]",
      strengths: ["[Point fort 1]", "[Point fort 2]"],
      weaknesses: ["[Point faible 1]", "[Point faible 2]", "[Point faible 3]"],
      recommendations: ["[Recommandation 1]", "[Recommandation 2]"],
    },
    {
      slug: "breakdown-restaurant",
      title: "[Nom du restaurant] — Website Review",
      category: "Restaurant",
      uxScore: 5,
      summary: "[À compléter.]",
      strengths: ["[Point fort 1]"],
      weaknesses: ["[Point faible 1]", "[Point faible 2]"],
      recommendations: ["[Recommandation 1]", "[Recommandation 2]"],
    },
    {
      slug: "breakdown-healthcare",
      title: "[Nom de la clinique] — Website Review",
      category: "Healthcare",
      uxScore: 7,
      summary: "[À compléter.]",
      strengths: ["[Point fort 1]", "[Point fort 2]"],
      weaknesses: ["[Point faible 1]"],
      recommendations: ["[Recommandation 1]"],
    },
    {
      slug: "breakdown-real-estate",
      title: "[Nom de l'agence] — Website Review",
      category: "Real Estate",
      uxScore: 4,
      summary: "[À compléter.]",
      strengths: ["[Point fort 1]"],
      weaknesses: ["[Point faible 1]", "[Point faible 2]", "[Point faible 3]"],
      recommendations: ["[Recommandation 1]", "[Recommandation 2]"],
    },
    {
      slug: "breakdown-saas",
      title: "[Nom du SaaS] — Website Review",
      category: "SaaS",
      uxScore: 8,
      summary: "[À compléter.]",
      strengths: ["[Point fort 1]", "[Point fort 2]"],
      weaknesses: ["[Point faible 1]"],
      recommendations: ["[Recommandation 1]"],
    },
  ],
  en: [
    {
      slug: "breakdown-gym",
      title: "[Gym name] — Website Review",
      category: "Gym",
      uxScore: 6,
      summary: "[Summary of the main UX problem identified on this gym website.]",
      strengths: ["[Strength 1]", "[Strength 2]"],
      weaknesses: ["[Weakness 1]", "[Weakness 2]", "[Weakness 3]"],
      recommendations: ["[Recommendation 1]", "[Recommendation 2]"],
    },
    {
      slug: "breakdown-restaurant",
      title: "[Restaurant name] — Website Review",
      category: "Restaurant",
      uxScore: 5,
      summary: "[To complete.]",
      strengths: ["[Strength 1]"],
      weaknesses: ["[Weakness 1]", "[Weakness 2]"],
      recommendations: ["[Recommendation 1]", "[Recommendation 2]"],
    },
    {
      slug: "breakdown-healthcare",
      title: "[Clinic name] — Website Review",
      category: "Healthcare",
      uxScore: 7,
      summary: "[To complete.]",
      strengths: ["[Strength 1]", "[Strength 2]"],
      weaknesses: ["[Weakness 1]"],
      recommendations: ["[Recommendation 1]"],
    },
    {
      slug: "breakdown-real-estate",
      title: "[Agency name] — Website Review",
      category: "Real Estate",
      uxScore: 4,
      summary: "[To complete.]",
      strengths: ["[Strength 1]"],
      weaknesses: ["[Weakness 1]", "[Weakness 2]", "[Weakness 3]"],
      recommendations: ["[Recommendation 1]", "[Recommendation 2]"],
    },
    {
      slug: "breakdown-saas",
      title: "[SaaS name] — Website Review",
      category: "SaaS",
      uxScore: 8,
      summary: "[To complete.]",
      strengths: ["[Strength 1]", "[Strength 2]"],
      weaknesses: ["[Weakness 1]"],
      recommendations: ["[Recommendation 1]"],
    },
  ],
  ar: [
    {
      slug: "breakdown-gym",
      title: "[اسم صالة الرياضة] — مراجعة الموقع",
      category: "صالة رياضية",
      uxScore: 6,
      summary: "[ملخص المشكلة الرئيسية في تجربة المستخدم المحددة على هذا الموقع الرياضي.]",
      strengths: ["[نقطة قوة 1]", "[نقطة قوة 2]"],
      weaknesses: ["[نقطة ضعف 1]", "[نقطة ضعف 2]", "[نقطة ضعف 3]"],
      recommendations: ["[توصية 1]", "[توصية 2]"],
    },
    {
      slug: "breakdown-restaurant",
      title: "[اسم المطعم] — مراجعة الموقع",
      category: "مطعم",
      uxScore: 5,
      summary: "[أكمل هذا القسم.]",
      strengths: ["[نقطة قوة 1]"],
      weaknesses: ["[نقطة ضعف 1]", "[نقطة ضعف 2]"],
      recommendations: ["[توصية 1]", "[توصية 2]"],
    },
    {
      slug: "breakdown-healthcare",
      title: "[اسم العيادة] — مراجعة الموقع",
      category: "الرعاية الصحية",
      uxScore: 7,
      summary: "[أكمل هذا القسم.]",
      strengths: ["[نقطة قوة 1]", "[نقطة قوة 2]"],
      weaknesses: ["[نقطة ضعف 1]"],
      recommendations: ["[توصية 1]"],
    },
    {
      slug: "breakdown-real-estate",
      title: "[اسم الوكالة] — مراجعة الموقع",
      category: "العقارات",
      uxScore: 4,
      summary: "[أكمل هذا القسم.]",
      strengths: ["[نقطة قوة 1]"],
      weaknesses: ["[نقطة ضعف 1]", "[نقطة ضعف 2]", "[نقطة ضعف 3]"],
      recommendations: ["[توصية 1]", "[توصية 2]"],
    },
    {
      slug: "breakdown-saas",
      title: "[اسم منتج SaaS] — مراجعة الموقع",
      category: "SaaS",
      uxScore: 8,
      summary: "[أكمل هذا القسم.]",
      strengths: ["[نقطة قوة 1]", "[نقطة قوة 2]"],
      weaknesses: ["[نقطة ضعف 1]"],
      recommendations: ["[توصية 1]"],
    },
  ],
};

export function getBreakdowns(locale: Locale): Breakdown[] {
  return breakdownsByLocale[locale];
}
