import type { CaseStudy } from "@/types/content";
import type { Locale } from "@/lib/i18n/config";

/**
 * Titres, tags, catégories et technologies sont réels.
 * Les champs narratifs (summary, overview, challenge, approach, keyInsights,
 * solution, outcome, lessonsLearned) sont encore des placeholders — à
 * remplacer par les vrais détails de chaque projet avant publication.
 */
const placeholderSection = {
  fr: { intro: "[À compléter.]", points: ["[Point à compléter.]", "[Point à compléter.]", "[Point à compléter.]"] },
  en: { intro: "[To complete.]", points: ["[Point to complete.]", "[Point to complete.]", "[Point to complete.]"] },
  ar: { intro: "[أكمل هذا القسم.]", points: ["[نقطة للإكمال.]", "[نقطة للإكمال.]", "[نقطة للإكمال.]"] },
};

const placeholderList = {
  fr: ["[Point à compléter.]", "[Point à compléter.]", "[Point à compléter.]"],
  en: ["[Point to complete.]", "[Point to complete.]", "[Point to complete.]"],
  ar: ["[نقطة للإكمال.]", "[نقطة للإكمال.]", "[نقطة للإكمال.]"],
};

const caseStudiesByLocale: Record<Locale, CaseStudy[]> = {
  fr: [
    {
      slug: "easyfitness-uae",
      title: "EasyFitness UAE",
      tagline:
        "Transformer un site de fitness en une expérience digitale orientée conversion.",
      tags: ["Audit UX", "Analyse UI", "Stratégie Produit", "Optimisation de la Conversion"],
      client: "Audit indépendant — non commandité",
      category: "Audit UX · Refonte UI",
      thumbnail: "/case-studies/easyfitness.jpg",
      summary: "[Résumé en une phrase du problème identifié et du résultat visé.]",
      overview: "[À compléter : présentation du projet et de son contexte.]",
      challenge: "[À compléter : quel problème UX/business ce projet devait résoudre.]",
      approach: placeholderSection.fr,
      keyInsights: placeholderList.fr,
      solution: placeholderSection.fr,
      outcome: placeholderSection.fr,
      lessonsLearned: "[À compléter.]",
      technologies: ["Figma", "Recherche UX", "Analyse Produit", "Wireframing", "Architecture de l'information"],
    },
    {
      slug: "konekta",
      title: "Konekta",
      tagline:
        "Concevoir un marketplace qui connecte entreprises et clients africains à travers de meilleures expériences digitales.",
      tags: ["Product Design", "Flutter", "Marketplace", "Stratégie UX"],
      client: "Projet personnel",
      category: "Product Design · Flutter",
      thumbnail: "/case-studies/konekta.jpg",
      summary: "[Résumé en une phrase du problème identifié et du résultat visé.]",
      overview: "[À compléter : présentation du projet et de son contexte.]",
      challenge: "[À compléter : quel problème UX/business ce projet devait résoudre.]",
      approach: placeholderSection.fr,
      keyInsights: placeholderList.fr,
      solution: placeholderSection.fr,
      outcome: placeholderSection.fr,
      lessonsLearned: "[À compléter.]",
      technologies: ["Flutter", "Firebase", "REST APIs", "Stratégie Produit", "Design UX", "Git"],
    },
    {
      slug: "igc-video-translation",
      title: "IGC",
      tagline:
        "Rendre le contenu éducatif accessible dans plusieurs langues grâce à la localisation par IA.",
      tags: ["Workflow IA", "Localisation", "Collaboration Produit"],
      client: "Collaboration produit",
      category: "Workflow IA · Localisation",
      thumbnail: "/case-studies/igc.jpg",
      summary: "[Résumé en une phrase du problème identifié et du résultat visé.]",
      overview: "[À compléter : présentation du projet et de son contexte.]",
      challenge: "[À compléter : quel problème UX/business ce projet devait résoudre.]",
      approach: placeholderSection.fr,
      keyInsights: placeholderList.fr,
      solution: placeholderSection.fr,
      outcome: placeholderSection.fr,
      lessonsLearned: "[À compléter.]",
      technologies: ["Traduction assistée par IA", "Localisation", "Conception de workflow", "Assurance qualité", "Collaboration Produit"],
    },
  ],
  en: [
    {
      slug: "easyfitness-uae",
      title: "EasyFitness UAE",
      tagline: "Transforming a fitness website into a conversion-focused digital experience.",
      tags: ["UX Audit", "UI Analysis", "Product Strategy", "Conversion Optimization"],
      client: "Independent audit — not a commissioned engagement",
      category: "UX Audit · UI Redesign",
      thumbnail: "/case-studies/easyfitness.jpg",
      summary: "[One-sentence summary of the problem identified and the target result.]",
      overview: "[To complete: project presentation and context.]",
      challenge: "[To complete: what UX/business problem this project needed to solve.]",
      approach: placeholderSection.en,
      keyInsights: placeholderList.en,
      solution: placeholderSection.en,
      outcome: placeholderSection.en,
      lessonsLearned: "[To complete.]",
      technologies: ["Figma", "UX Research", "Product Analysis", "Wireframing", "Information Architecture"],
    },
    {
      slug: "konekta",
      title: "Konekta",
      tagline:
        "Designing a marketplace that connects African businesses and customers through better digital experiences.",
      tags: ["Product Design", "Flutter", "Marketplace", "UX Strategy"],
      client: "Personal project",
      category: "Product Design · Flutter",
      thumbnail: "/case-studies/konekta.jpg",
      summary: "[One-sentence summary of the problem identified and the target result.]",
      overview: "[To complete: project presentation and context.]",
      challenge: "[To complete: what UX/business problem this project needed to solve.]",
      approach: placeholderSection.en,
      keyInsights: placeholderList.en,
      solution: placeholderSection.en,
      outcome: placeholderSection.en,
      lessonsLearned: "[To complete.]",
      technologies: ["Flutter", "Firebase", "REST APIs", "Product Strategy", "UX Design", "Git"],
    },
    {
      slug: "igc-video-translation",
      title: "IGC",
      tagline: "Making educational content accessible across languages through AI-powered localization.",
      tags: ["AI Workflow", "Localization", "Product Collaboration"],
      client: "Product collaboration",
      category: "AI Workflow · Localization",
      thumbnail: "/case-studies/igc.jpg",
      summary: "[One-sentence summary of the problem identified and the target result.]",
      overview: "[To complete: project presentation and context.]",
      challenge: "[To complete: what UX/business problem this project needed to solve.]",
      approach: placeholderSection.en,
      keyInsights: placeholderList.en,
      solution: placeholderSection.en,
      outcome: placeholderSection.en,
      lessonsLearned: "[To complete.]",
      technologies: ["AI-assisted Translation", "Localization", "Workflow Design", "Quality Assurance", "Product Collaboration"],
    },
  ],
  ar: [
    {
      slug: "easyfitness-uae",
      title: "EasyFitness UAE",
      tagline: "تحويل موقع لياقة بدنية إلى تجربة رقمية موجهة نحو التحويل.",
      tags: ["تدقيق تجربة المستخدم", "تحليل الواجهة", "استراتيجية المنتج", "تحسين التحويل"],
      client: "تدقيق مستقل — غير مُكلَّف من قبل العميل",
      category: "تدقيق تجربة المستخدم · إعادة تصميم الواجهة",
      thumbnail: "/case-studies/easyfitness.jpg",
      summary: "[ملخص بجملة واحدة للمشكلة المحددة والنتيجة المستهدفة.]",
      overview: "[أكمل هذا القسم: تقديم المشروع وسياقه.]",
      challenge: "[أكمل هذا القسم: ما المشكلة التي كان على هذا المشروع حلها.]",
      approach: placeholderSection.ar,
      keyInsights: placeholderList.ar,
      solution: placeholderSection.ar,
      outcome: placeholderSection.ar,
      lessonsLearned: "[أكمل هذا القسم.]",
      technologies: ["Figma", "بحث تجربة المستخدم", "تحليل المنتج", "Wireframing", "هندسة المعلومات"],
    },
    {
      slug: "konekta",
      title: "Konekta",
      tagline: "تصميم سوق إلكتروني يربط الشركات والعملاء الأفارقة من خلال تجارب رقمية أفضل.",
      tags: ["تصميم المنتج", "Flutter", "السوق الإلكتروني", "استراتيجية تجربة المستخدم"],
      client: "مشروع شخصي",
      category: "تصميم المنتج · Flutter",
      thumbnail: "/case-studies/konekta.jpg",
      summary: "[ملخص بجملة واحدة للمشكلة المحددة والنتيجة المستهدفة.]",
      overview: "[أكمل هذا القسم: تقديم المشروع وسياقه.]",
      challenge: "[أكمل هذا القسم: ما المشكلة التي كان على هذا المشروع حلها.]",
      approach: placeholderSection.ar,
      keyInsights: placeholderList.ar,
      solution: placeholderSection.ar,
      outcome: placeholderSection.ar,
      lessonsLearned: "[أكمل هذا القسم.]",
      technologies: ["Flutter", "Firebase", "REST APIs", "استراتيجية المنتج", "تصميم تجربة المستخدم", "Git"],
    },
    {
      slug: "igc-video-translation",
      title: "IGC",
      tagline: "إتاحة الوصول إلى المحتوى التعليمي بلغات متعددة من خلال الترجمة المحلية المدعومة بالذكاء الاصطناعي.",
      tags: ["سير عمل بالذكاء الاصطناعي", "الترجمة المحلية", "تعاون على المنتج"],
      client: "تعاون على المنتج",
      category: "سير عمل بالذكاء الاصطناعي · الترجمة المحلية",
      thumbnail: "/case-studies/igc.jpg",
      summary: "[ملخص بجملة واحدة للمشكلة المحددة والنتيجة المستهدفة.]",
      overview: "[أكمل هذا القسم: تقديم المشروع وسياقه.]",
      challenge: "[أكمل هذا القسم: ما المشكلة التي كان على هذا المشروع حلها.]",
      approach: placeholderSection.ar,
      keyInsights: placeholderList.ar,
      solution: placeholderSection.ar,
      outcome: placeholderSection.ar,
      lessonsLearned: "[أكمل هذا القسم.]",
      technologies: ["ترجمة بمساعدة الذكاء الاصطناعي", "الترجمة المحلية", "تصميم سير العمل", "ضمان الجودة", "التعاون على المنتج"],
    },
  ],
};

export function getCaseStudies(locale: Locale): CaseStudy[] {
  return caseStudiesByLocale[locale];
}
